import java.io.IOException;
class P4
{
	void fn() throws Exception {
		System.out.println("Parent with Parent Exception declared");
	}
}
class C4 extends P4{
	void fn() { //parent with Compile exception, child also no exception
		System.out.println("Parent with Parent Exception declared "
				+ "plus child no exception declared");
	}
}
class D4 extends P4{
	void fn() throws NumberFormatException { //parent with runtime exception, child has Runtime exception
		System.out.println("Parent with Parent Exception declared "
				+ "plus child has Runtime exception declared");
	}
}
class E4 extends P4{
	void fn() throws IOException { 
		System.out.println("Parent with Parent Exception declared "
				+ "plus child has same Compile exception declared");
	}
}
class F4 extends P4{
	void fn() throws java.sql.SQLException { 
		System.out.println("Parent with Parent Exception declared "
				+ "plus child has different Compile exception declared");
	}
}
class G4 extends P4 {
	
	void fn() throws Exception { 
		System.out.println("Parent with Parent Exception declared "
				+ "plus child has parent exception declared");
	}
}


public class ExcepEg10 {

	public static void main(String[] args) throws Exception {
		P4 p1=new P4();
		p1.fn();
		P4 p2=new C4();
		p2.fn();
		P4 p3=new D4();
		p3.fn();
		P4 p4=new E4();
		p4.fn();
		P4 p5=new F4();
		p5.fn();
		P4 p6=new G4();
		p6.fn();
		

	}

}

































import java.io.*;
class P3
{
	void fn() throws IOException {
		System.out.println("Parent with Compile exception declared");
	}
}
class C3 extends P3{
	void fn() { //parent with Compile exception, child also no exception
		System.out.println("Parent with Compile exception declared "
				+ "plus child no exception declared");
	}
}
class D3 extends P3{
	void fn() throws NumberFormatException { //parent with runtime exception, child has Runtime exception
		System.out.println("Parent with Compile exception declared "
				+ "plus child has Runtime exception declared");
	}
}
class E3 extends P3{
	void fn() throws IOException { //parent with Compile exception, child has Compile time exception
		System.out.println("Parent with Compile exception declared "
				+ "plus child has same Compile exception declared");
	}
}
//class E32 extends P3{
//	void fn() throws java.sql.SQLException { //parent with Compile exception, child has Compile time exception
//		System.out.println("Parent with Compile exception declared "
//				+ "plus child has different Compile exception declared");
//	}
//}
//class F3 extends P3 {
//	// Not allowed
//	void fn() throws Exception { // parent with Compile exception, child has Parent
//									// time exception
//		System.out.println("Parent with Compile exception declared "
//				+ "plus child has parent exception declared");
//	}
//}


public class ExcepEg9 {

	public static void main(String[] args) throws IOException {
		P3 p1=new P3();
		p1.fn();
		P3 p2=new C3();
		p2.fn();
		P3 p3=new D3();
		p3.fn();
		

	}

}


































import java.io.*;
class P2
{
	void fn() throws ArithmeticException {
		System.out.println("Parent with Runtime exception declared");
	}
}
class C2 extends P2{
	void fn() { //parent with Runtime exception, child also no exception
		System.out.println("Parent with Runtime exception declared "
				+ "plus child no exception declared");
	}
}
class D2 extends P2{
	void fn() throws NumberFormatException { //parent with runtime exception, child has Runtime exception
		System.out.println("Parent with Runtime exception declared "
				+ "plus child has Runtime exception declared");
	}
}
//class E2 extends P2{
//	//Not allowed
//	void fn() throws IOException { //parent with no exception, child has Compile time exception
//		System.out.println("Parent with Runtime exception declared "
//				+ "plus child has Compile exception declared");
//	}
//}
//class F2 extends P2 {
//	// Not allowed
//	void fn() throws Exception { // parent with no exception, child has Compile
//									// time exception
//		System.out.println("Parent with Runtime exception declared "
//				+ "plus child has parent exception declared");
//	}
//}


public class ExcepEg8 {

	public static void main(String[] args) {
		P2 p1=new P2();
		p1.fn();
		P2 p2=new C2();
		p2.fn();
		P2 p3=new D2();
		p3.fn();
		

	}

}









































import java.io.*;
class P
{
	void fn() {
		System.out.println("Parent with no exception declared");
	}
}
class C extends P{
	void fn() { //parent with no exception, child also no exception
		System.out.println("Parent with no exception declared "
				+ "plus child also no exception declared");
	}
}
class D extends P{
	void fn() throws ArithmeticException { //parent with no exception, child has Runtime exception
		System.out.println("Parent with no exception declared "
				+ "plus child has Runtime exception declared");
	}
}
//class E extends P{
//	//Not allowed
//	void fn() throws IOException { //parent with no exception, child has Compile time exception
//		System.out.println("Parent with no exception declared "
//				+ "plus child has Compile exception declared");
//	}
//}


public class ExcepEg7 {

	public static void main(String[] args) {
		P p1=new P();
		p1.fn();
		P p2=new C();
		p2.fn();
		P p3=new D();
		p3.fn();
		

	}

}
